# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: html2mobi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import articlescrape_pb2 as articlescrape__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='html2mobi.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fhtml2mobi.proto\x1a\x13\x61rticlescrape.proto\"\x14\n\x04MOBI\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x32\'\n\tHTML2MOBI\x12\x1a\n\x07\x43onvert\x12\x08.Article\x1a\x05.MOBIb\x06proto3'
  ,
  dependencies=[articlescrape__pb2.DESCRIPTOR,])




_MOBI = _descriptor.Descriptor(
  name='MOBI',
  full_name='MOBI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='MOBI.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['MOBI'] = _MOBI
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MOBI = _reflection.GeneratedProtocolMessageType('MOBI', (_message.Message,), {
  'DESCRIPTOR' : _MOBI,
  '__module__' : 'html2mobi_pb2'
  # @@protoc_insertion_point(class_scope:MOBI)
  })
_sym_db.RegisterMessage(MOBI)



_HTML2MOBI = _descriptor.ServiceDescriptor(
  name='HTML2MOBI',
  full_name='HTML2MOBI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=62,
  serialized_end=101,
  methods=[
  _descriptor.MethodDescriptor(
    name='Convert',
    full_name='HTML2MOBI.Convert',
    index=0,
    containing_service=None,
    input_type=articlescrape__pb2._ARTICLE,
    output_type=_MOBI,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HTML2MOBI)

DESCRIPTOR.services_by_name['HTML2MOBI'] = _HTML2MOBI

# @@protoc_insertion_point(module_scope)
