"""empty message

Revision ID: 639a526a5ea5
Revises: 8f4398960398
Create Date: 2020-05-04 13:45:09.907106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639a526a5ea5'
down_revision = '8f4398960398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified')
    # ### end Alembic commands ###
