"""empty message

Revision ID: c3574f8c022b
Revises: 2914dc50542f
Create Date: 2020-05-04 12:09:58.854441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3574f8c022b'
down_revision = '2914dc50542f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'token',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'token',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
