# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: email.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='email.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65mail.proto\"\xa1\x01\n\x0c\x45mailMessage\x12\x19\n\x02to\x18\x01 \x03(\x0b\x32\r.EmailAddress\x12\x1d\n\x06sender\x18\x02 \x01(\x0b\x32\r.EmailAddress\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x11\n\tbody_text\x18\x04 \x01(\t\x12\x11\n\tbody_html\x18\x05 \x01(\t\x12 \n\x0b\x61ttachments\x18\x06 \x03(\x0b\x32\x0b.Attachment\"!\n\rEmailResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"+\n\x0c\x45mailAddress\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"(\n\nAttachment\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t2.\n\x05\x45mail\x12%\n\x04Send\x12\r.EmailMessage\x1a\x0e.EmailResponseb\x06proto3'
)




_EMAILMESSAGE = _descriptor.Descriptor(
  name='EmailMessage',
  full_name='EmailMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='to', full_name='EmailMessage.to', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='EmailMessage.sender', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='EmailMessage.subject', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body_text', full_name='EmailMessage.body_text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body_html', full_name='EmailMessage.body_html', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attachments', full_name='EmailMessage.attachments', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=177,
)


_EMAILRESPONSE = _descriptor.Descriptor(
  name='EmailResponse',
  full_name='EmailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='EmailResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=212,
)


_EMAILADDRESS = _descriptor.Descriptor(
  name='EmailAddress',
  full_name='EmailAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='EmailAddress.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='EmailAddress.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=257,
)


_ATTACHMENT = _descriptor.Descriptor(
  name='Attachment',
  full_name='Attachment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='Attachment.file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Attachment.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=299,
)

_EMAILMESSAGE.fields_by_name['to'].message_type = _EMAILADDRESS
_EMAILMESSAGE.fields_by_name['sender'].message_type = _EMAILADDRESS
_EMAILMESSAGE.fields_by_name['attachments'].message_type = _ATTACHMENT
DESCRIPTOR.message_types_by_name['EmailMessage'] = _EMAILMESSAGE
DESCRIPTOR.message_types_by_name['EmailResponse'] = _EMAILRESPONSE
DESCRIPTOR.message_types_by_name['EmailAddress'] = _EMAILADDRESS
DESCRIPTOR.message_types_by_name['Attachment'] = _ATTACHMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailMessage = _reflection.GeneratedProtocolMessageType('EmailMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMAILMESSAGE,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:EmailMessage)
  })
_sym_db.RegisterMessage(EmailMessage)

EmailResponse = _reflection.GeneratedProtocolMessageType('EmailResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMAILRESPONSE,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:EmailResponse)
  })
_sym_db.RegisterMessage(EmailResponse)

EmailAddress = _reflection.GeneratedProtocolMessageType('EmailAddress', (_message.Message,), {
  'DESCRIPTOR' : _EMAILADDRESS,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:EmailAddress)
  })
_sym_db.RegisterMessage(EmailAddress)

Attachment = _reflection.GeneratedProtocolMessageType('Attachment', (_message.Message,), {
  'DESCRIPTOR' : _ATTACHMENT,
  '__module__' : 'email_pb2'
  # @@protoc_insertion_point(class_scope:Attachment)
  })
_sym_db.RegisterMessage(Attachment)



_EMAIL = _descriptor.ServiceDescriptor(
  name='Email',
  full_name='Email',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=301,
  serialized_end=347,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='Email.Send',
    index=0,
    containing_service=None,
    input_type=_EMAILMESSAGE,
    output_type=_EMAILRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAIL)

DESCRIPTOR.services_by_name['Email'] = _EMAIL

# @@protoc_insertion_point(module_scope)
