# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import articlescrape_pb2 as articlescrape__pb2
import html2mobi_pb2 as html2mobi__pb2


class HTML2MOBIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_unary(
                '/HTML2MOBI/Convert',
                request_serializer=articlescrape__pb2.Article.SerializeToString,
                response_deserializer=html2mobi__pb2.MOBI.FromString,
                )


class HTML2MOBIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Convert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HTML2MOBIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=articlescrape__pb2.Article.FromString,
                    response_serializer=html2mobi__pb2.MOBI.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HTML2MOBI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HTML2MOBI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HTML2MOBI/Convert',
            articlescrape__pb2.Article.SerializeToString,
            html2mobi__pb2.MOBI.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
